### Hello World!
GET http://localhost:3000/

### Get All Apples
GET http://localhost:3000/api/apples

### Get Apples by ID
GET http://localhost:3000/api/apples/5

### Get Oranged by ID
GET http://localhost:3000/api/oranges/1

### Apple create
post http://localhost:3000/api/apples

{
   "purple",
   "notApple"
}